# Generated by Django 2.1.1 on 2018-09-14 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=120)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('dueTo', models.DateField()),
                ('owner', models.CharField(max_length=50)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
