# Generated by Django 2.1.2 on 2018-10-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
